### ISSUE TITLE
Blender 2.91 - Cannot find Object Category

### ISSUE THREAD

**Issue by justinaquinoGITB** [markus-ebke/SolarSystemSimulator#1]
Hi Markus, 
following the instruction in the planet.blend I cannot seem to find the Object Category needed to activate the Add On. Strangely the addon does  appear in my list of Addons after I install the Zip file. 

Ubuntu 20.04.1 Blender 2.91 (installed with Ubuntu Software Store).

**Comment by justinaquino** [comment]
Sorry figured it out. 
Object-Category is EDIT > PREFERENCES > select Add-on > beside the check box of Add-ons  go to Dropdown Category > Pick Objects > Pick also Community. 
Now it works.
